name: CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download Rom
      uses: pguyot/arm-runner-action@v2.4.0
      with:
        commands: |
          sudo apt update
          sudo apt install git
          sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
    - name: Install dependencies
      uses: pguyot/arm-runner-action@v2.4.0
      with:
        commands: |
          sudo apt update
          sudo apt install --no-install-recommends -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libwebp-dev libpoco-dev libncurses5-dev
    - name: Build Lua
      uses: pguyot/arm-runner-action@v2.4.0
      with:
        commands: |
         git submodule update --init --recursive
         make -C craftos2-lua linux -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Build CraftOS-PC
      uses: pguyot/arm-runner-action@v2.4.0
      with:
        commands: |
         CFLAGS=-Wall ./configure
         make -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Run CraftOSTest
      uses: pguyot/arm-runner-action@v2.4.0
      with:
        commands: | 
         ./craftos --headless --script resources/CraftOSTest.lua || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      uses: pguyot/arm-runner-action@v2.4.0
      with:
        commands: |
         cat ~/.local/share/craftos-pc/computer/0/CraftOSTest.log
         if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi
    
  build-basic:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM
      run: sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libpoco-dev
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure --without-ncurses --without-png --without-sdl_mixer --with-html
        make -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Run CraftOSTest
      run: ./craftos --headless --script resources/CraftOSTest.lua || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/CraftOSTest.log
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi

  build-standalone:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libwebp-dev libpoco-dev libncurses5-dev nodejs
    - name: Build standalone ROM
      run: |
        git clone https://github.com/MCJack123/craftos2-rom
        cd craftos2-rom
        node ../resources/packStandaloneROM.js
        cd ..
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure --with-standalone_rom=craftos2-rom/fs_standalone.cpp
        make -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Run CraftOSTest
      run: ./craftos --headless --script resources/CraftOSTest.lua || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/CraftOSTest.log
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi

  build-cct-test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM & CC:T
      run: |
        sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
        git clone --branch v1.16.5-1.100.0 https://github.com/SquidDev-CC/CC-Tweaked ../CC-Tweaked
        patch -p1 -d ../CC-Tweaked < resources/CCT-Tests.patch
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libwebp-dev libpoco-dev libncurses5-dev
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure
        make -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Run CC:T McFly Tests
      run: ./craftos --mount-ro test-rom=../CC-Tweaked/src/test/resources/test-rom --headless --script resources/CCT-Test-Bootstrap.lua || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/test-log.txt
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi
      
  build-windows:

    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM
      run: git clone https://github.com/MCJack123/craftos2-rom "C:\Program Files\CraftOS-PC"
    - name: Restore vcpkg cache
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 20907dc8bfd4a3baf555467727755fbba708ad84
    - name: Prepare environment
      run: |
        git submodule update --init --recursive
        mkdir x64\ReleaseC
        mkdir x64\Release
        & $Env:VCPKG_ROOT\vcpkg integrate install
        (Get-Content -path "$Env:VCPKG_ROOT\ports\poco\portfile.cmake") -replace "ENABLE_NETSSL_WIN", "FORCE_OPENSSL" | Set-Content -Path "$Env:VCPKG_ROOT\ports\poco\portfile.cmake"
    - name: Build CraftOS-PC
      run: |
        function Invoke-Environment {
            param
            (
                # Any cmd shell command, normally a configuration batch file.
                [Parameter(Mandatory=$true)]
                [string] $Command
            )

            $Command = "`"" + $Command + "`""
            cmd /c "$Command > nul 2>&1 && set" | . { process {
                if ($_ -match '^([^=]+)=(.*)') {
                    [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
                }
            }}

        }

        Invoke-Environment "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        $tag = git rev-parse --short HEAD
        Set-Item ENV:ExternalCompilerOptions /DCRAFTOSPC_COMMIT=\"$tag\"
        msbuild "CraftOS-PC 2.sln" /p:Configuration=ReleaseC
        # Remove buildtrees that kill the cache
        Remove-Item vcpkg\buildtrees\* -Force -Recurse -ErrorAction SilentlyContinue
    - name: Run CraftOSTest
      run: |
        x64\ReleaseC\CraftOS-PC --headless --script resources\CraftOSTest.lua --rom "C:\Program Files\CraftOS-PC"
        echo $LASTEXITCODE > retval.txt
      continue-on-error: true
    - name: Show logs
      run: |
        type "$ENV:APPDATA\CraftOS-PC\computer\0\CraftOSTest.log"
        $code = Get-Content .\retval.txt
        if ( $code -ne 0 ) { exit $code }
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: CraftOS-PC-Artifact
        path: |
          x64\ReleaseC\CraftOS-PC.exe
          x64\ReleaseC\lua51.dll
